use test;

drop index meas_vals_ind1 on meas_vals;
create index meas_vals_ind1 on meas_vals(meas_time);
drop index meas_vals_ind2 on meas_vals;
create index meas_vals_ind2 on meas_vals(agg_hour);
drop index meas_vals_ind3 on meas_vals;
create index meas_vals_ind3 on meas_vals(agg_day);
drop index meas_vals_ind4 on meas_vals;
create index meas_vals_ind4 on meas_vals(agg_week);
drop index meas_vals_ind5 on meas_vals;
create index meas_vals_ind5 on meas_vals(agg_month);
drop index meas_vals_ind6 on meas_vals;
create index meas_vals_ind6 on meas_vals(topid, Key1, meas_time);
drop index meas_vals_ind7 on meas_vals;
create index meas_vals_ind7 on meas_vals(topid, Key1, Key2, meas_time);
drop index meas_vals_ind8 on meas_vals;
create index meas_vals_ind8 on meas_vals(topid, Key1, Key2, Key3, meas_time);
drop index meas_vals_ind9 on meas_vals;
create index meas_vals_ind9 on meas_vals(topid, Key1, Key2, Key3, Key4, meas_time);
drop index meas_vals_ind10 on meas_vals;
create index meas_vals_ind10 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, meas_time);
drop index meas_vals_ind11 on meas_vals;
create index meas_vals_ind11 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, meas_time);
drop index meas_vals_ind12 on meas_vals;
create index meas_vals_ind12 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, meas_time);
drop index meas_vals_ind13 on meas_vals;
create index meas_vals_ind13 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, meas_time);
drop index meas_vals_ind14 on meas_vals;
create index meas_vals_ind14 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, meas_time);
drop index meas_vals_ind15 on meas_vals;
create index meas_vals_ind15 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, meas_time);
drop index meas_vals_ind16 on meas_vals;
create index meas_vals_ind16 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, meas_time);
drop index meas_vals_ind17 on meas_vals;
create index meas_vals_ind17 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, meas_time);
drop index meas_vals_ind18 on meas_vals;
create index meas_vals_ind18 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, meas_time);
drop index meas_vals_ind19 on meas_vals;
create index meas_vals_ind19 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, meas_time);
drop index meas_vals_ind20 on meas_vals;
create index meas_vals_ind20 on meas_vals(Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, Key15, meas_time);
drop index meas_vals_ind21 on meas_vals;
#create index meas_vals_ind21 on meas_vals(TopId);
drop index meas_vals_ind22 on meas_vals;
#create index meas_vals_ind22 on meas_vals(counter);
drop index meas_vals_ind23 on meas_vals;
#create index meas_vals_ind23 on meas_vals(val);

drop index topo_def_ind1 on topo_def;
#create index topo_def_ind1 on topo_def(TopId);
drop index topo_def_ind2 on topo_def;
#create index topo_def_ind2 on topo_def(TKey1);
drop index topo_def_ind3 on topo_def;
#create index topo_def_ind3 on topo_def(TKey1, TKey2);
drop index topo_def_ind4 on topo_def;
#create index topo_def_ind4 on topo_def(TKey1, TKey2, TKey3);
drop index topo_def_ind5 on topo_def;
#create index topo_def_ind5 on topo_def(TKey1, TKey2, TKey3, TKey4);
drop index topo_def_ind6 on topo_def;
#create index topo_def_ind6 on topo_def(TKey1, TKey2, TKey3, TKey4, TKey5);
drop index topo_def_ind7 on topo_def;
#create index topo_def_ind7 on topo_def(TKey1, TKey2, TKey3, TKey4, TKey5, TKey6);
drop index topo_def_ind8 on topo_def;
#create index topo_def_ind8 on topo_def(TKey1, TKey2, TKey3, TKey4, TKey5, TKey6, TKey7);
drop index topo_def_ind9 on topo_def;
#create index topo_def_ind9 on topo_def(TKey1, TKey2, TKey3, TKey4, TKey5, TKey6, TKey7, TKey8);
drop index topo_def_ind10 on topo_def;
#create index topo_def_ind10 on topo_def(TKey1, TKey2, TKey3, TKey4, TKey5, TKey6, TKey7, TKey8, TKey9);
drop index topo_def_ind11 on topo_def;
#create index topo_def_ind11 on topo_def(TKey1, TKey2, TKey3, TKey4, TKey5, TKey6, TKey7, TKey8, TKey9, TKey10);
drop index topo_def_ind12 on topo_def;
#create index topo_def_ind12 on topo_def(TKey1, TKey2, TKey3, TKey4, TKey5, TKey6, TKey7, TKey8, TKey9, TKey10, TKey11);
drop index topo_def_ind13 on topo_def;
#create index topo_def_ind13 on topo_def(TKey1, TKey2, TKey3, TKey4, TKey5, TKey6, TKey7, TKey8, TKey9, TKey10, TKey11, TKey12);
drop index topo_def_ind14 on topo_def;
#create index topo_def_ind14 on topo_def(TKey1, TKey2, TKey3, TKey4, TKey5, TKey6, TKey7, TKey8, TKey9, TKey10, TKey11, TKey12, TKey13);
drop index topo_def_ind15 on topo_def;
#create index topo_def_ind15 on topo_def(TKey1, TKey2, TKey3, TKey4, TKey5, TKey6, TKey7, TKey8, TKey9, TKey10, TKey11, TKey12, TKey13, TKey14);
drop index topo_def_ind16 on topo_def;
#create index topo_def_ind16 on topo_def(TKey1, TKey2, TKey3, TKey4, TKey5, TKey6, TKey7, TKey8, TKey9, TKey10, TKey11, TKey12, TKey13, TKey14, TKey15);

drop index topo_desc_ind1 on topo_desc;
#create index topo_desc_ind1 on topo_desc(TopId);

drop index count_desc_ind1 on count_desc;
#create index count_desc_ind1 on count_desc(TopId);
drop index count_desc_ind2 on count_desc;
#create index count_desc_ind2 on count_desc(counter);

drop index meas_types_ind1 on meas_types;
#create index meas_types_ind1 on meas_types(TopId);
drop index meas_types_ind2 on meas_types;
#create index meas_types_ind2 on meas_types(counter);

drop index hourly_agg_ind1 on hourly_agg;
create index hourly_agg_ind1 on hourly_agg(topid, Key1, time_hour);
drop index hourly_agg_ind2 on hourly_agg;
create index hourly_agg_ind2 on hourly_agg(topid, Key1, Key2, time_hour);
drop index hourly_agg_ind3 on hourly_agg;
create index hourly_agg_ind3 on hourly_agg(topid, Key1, Key2, Key3, time_hour);
drop index hourly_agg_ind4 on hourly_agg;
create index hourly_agg_ind4 on hourly_agg(topid, Key1, Key2, Key3, Key4, time_hour);
drop index hourly_agg_ind5 on hourly_agg;
create index hourly_agg_ind5 on hourly_agg(topid, Key1, Key2, Key3, Key4, Key5, time_hour);
drop index hourly_agg_ind6 on hourly_agg;
create index hourly_agg_ind6 on hourly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, time_hour);
drop index hourly_agg_ind7 on hourly_agg;
create index hourly_agg_ind7 on hourly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, time_hour);
drop index hourly_agg_ind8 on hourly_agg;
create index hourly_agg_ind8 on hourly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, time_hour);
drop index hourly_agg_ind9 on hourly_agg;
create index hourly_agg_ind9 on hourly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, time_hour);
drop index hourly_agg_ind10 on hourly_agg;
create index hourly_agg_ind10 on hourly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, time_hour);
drop index hourly_agg_ind11 on hourly_agg;
create index hourly_agg_ind11 on hourly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, time_hour);
drop index hourly_agg_ind12 on hourly_agg;
create index hourly_agg_ind12 on hourly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, time_hour);
drop index hourly_agg_ind13 on hourly_agg;
create index hourly_agg_ind13 on hourly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, time_hour);
drop index hourly_agg_ind14 on hourly_agg;
create index hourly_agg_ind14 on hourly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, time_hour);
drop index hourly_agg_ind15 on hourly_agg;
create index hourly_agg_ind15 on hourly_agg(Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, Key15, time_hour);
drop index hourly_agg_ind16 on hourly_agg;
#create index hourly_agg_ind16 on hourly_agg(TopId);
drop index hourly_agg_ind17 on hourly_agg;
#create index hourly_agg_ind17 on hourly_agg(counter);
drop index hourly_agg_ind18 on hourly_agg;
#create index hourly_agg_ind18 on hourly_agg(time_hour);
drop index hourly_agg_ind19 on hourly_agg;
#create index hourly_agg_ind19 on hourly_agg(agg_type);
drop index hourly_agg_ind20 on hourly_agg;
#create index hourly_agg_ind20 on hourly_agg(countTopId);

drop index daily_agg_ind1 on daily_agg;
create index daily_agg_ind1 on daily_agg(topid, Key1, time_day);
drop index daily_agg_ind2 on daily_agg;
create index daily_agg_ind2 on daily_agg(topid, Key1, Key2, time_day);
drop index daily_agg_ind3 on daily_agg;
create index daily_agg_ind3 on daily_agg(topid, Key1, Key2, Key3, time_day);
drop index daily_agg_ind4 on daily_agg;
create index daily_agg_ind4 on daily_agg(topid, Key1, Key2, Key3, Key4, time_day);
drop index daily_agg_ind5 on daily_agg;
create index daily_agg_ind5 on daily_agg(topid, Key1, Key2, Key3, Key4, Key5, time_day);
drop index daily_agg_ind6 on daily_agg;
create index daily_agg_ind6 on daily_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, time_day);
drop index daily_agg_ind7 on daily_agg;
create index daily_agg_ind7 on daily_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, time_day);
drop index daily_agg_ind8 on daily_agg;
create index daily_agg_ind8 on daily_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, time_day);
drop index daily_agg_ind9 on daily_agg;
create index daily_agg_ind9 on daily_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, time_day);
drop index daily_agg_ind10 on daily_agg;
create index daily_agg_ind10 on daily_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, time_day);
drop index daily_agg_ind11 on daily_agg;
create index daily_agg_ind11 on daily_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, time_day);
drop index daily_agg_ind12 on daily_agg;
create index daily_agg_ind12 on daily_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, time_day);
drop index daily_agg_ind13 on daily_agg;
create index daily_agg_ind13 on daily_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, time_day);
drop index daily_agg_ind14 on daily_agg;
create index daily_agg_ind14 on daily_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, time_day);
drop index daily_agg_ind15 on daily_agg;
create index daily_agg_ind15 on daily_agg(Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, Key15, time_day);
drop index daily_agg_ind16 on daily_agg;
#create index daily_agg_ind16 on daily_agg(TopId);
drop index daily_agg_ind17 on daily_agg;
#create index daily_agg_ind17 on daily_agg(counter);
drop index daily_agg_ind18 on daily_agg;
#create index daily_agg_ind18 on daily_agg(time_day);
drop index daily_agg_ind19 on daily_agg;
#create index daily_agg_ind19 on daily_agg(agg_type);
drop index daily_agg_ind20 on daily_agg;
#create index daily_agg_ind20 on daily_agg(countTopId);

drop index weekly_agg_ind1 on weekly_agg;
create index weekly_agg_ind1 on weekly_agg(topid, Key1, time_week);
drop index weekly_agg_ind2 on weekly_agg;
create index weekly_agg_ind2 on weekly_agg(topid, Key1, Key2, time_week);
drop index weekly_agg_ind3 on weekly_agg;
create index weekly_agg_ind3 on weekly_agg(topid, Key1, Key2, Key3, time_week);
drop index weekly_agg_ind4 on weekly_agg;
create index weekly_agg_ind4 on weekly_agg(topid, Key1, Key2, Key3, Key4, time_week);
drop index weekly_agg_ind5 on weekly_agg;
create index weekly_agg_ind5 on weekly_agg(topid, Key1, Key2, Key3, Key4, Key5, time_week);
drop index weekly_agg_ind6 on weekly_agg;
create index weekly_agg_ind6 on weekly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, time_week);
drop index weekly_agg_ind7 on weekly_agg;
create index weekly_agg_ind7 on weekly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, time_week);
drop index weekly_agg_ind8 on weekly_agg;
create index weekly_agg_ind8 on weekly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, time_week);
drop index weekly_agg_ind9 on weekly_agg;
create index weekly_agg_ind9 on weekly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, time_week);
drop index weekly_agg_ind10 on weekly_agg;
create index weekly_agg_ind10 on weekly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, time_week);
drop index weekly_agg_ind11 on weekly_agg;
create index weekly_agg_ind11 on weekly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, time_week);
drop index weekly_agg_ind12 on weekly_agg;
create index weekly_agg_ind12 on weekly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, time_week);
drop index weekly_agg_ind13 on weekly_agg;
create index weekly_agg_ind13 on weekly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, time_week);
drop index weekly_agg_ind14 on weekly_agg;
create index weekly_agg_ind14 on weekly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, time_week);
drop index weekly_agg_ind15 on weekly_agg;
create index weekly_agg_ind15 on weekly_agg(Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, Key15, time_week);
drop index weekly_agg_ind16 on weekly_agg;
#create index weekly_agg_ind16 on weekly_agg(TopId);
drop index weekly_agg_ind17 on weekly_agg;
#create index weekly_agg_ind17 on weekly_agg(counter);
drop index weekly_agg_ind18 on weekly_agg;
#create index weekly_agg_ind18 on weekly_agg(time_week);
drop index weekly_agg_ind19 on weekly_agg;
#create index weekly_agg_ind19 on weekly_agg(agg_type);
drop index weekly_agg_ind20 on weekly_agg;
#create index weekly_agg_ind20 on weekly_agg(countTopId);

drop index monthly_agg_ind1 on monthly_agg;
create index monthly_agg_ind1 on monthly_agg(topid, Key1, time_month);
drop index monthly_agg_ind2 on monthly_agg;
create index monthly_agg_ind2 on monthly_agg(topid, Key1, Key2, time_month);
drop index monthly_agg_ind3 on monthly_agg;
create index monthly_agg_ind3 on monthly_agg(topid, Key1, Key2, Key3, time_month);
drop index monthly_agg_ind4 on monthly_agg;
create index monthly_agg_ind4 on monthly_agg(topid, Key1, Key2, Key3, Key4, time_month);
drop index monthly_agg_ind5 on monthly_agg;
create index monthly_agg_ind5 on monthly_agg(topid, Key1, Key2, Key3, Key4, Key5, time_month);
drop index monthly_agg_ind6 on monthly_agg;
create index monthly_agg_ind6 on monthly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, time_month);
drop index monthly_agg_ind7 on monthly_agg;
create index monthly_agg_ind7 on monthly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, time_month);
drop index monthly_agg_ind8 on monthly_agg;
create index monthly_agg_ind8 on monthly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, time_month);
drop index monthly_agg_ind9 on monthly_agg;
create index monthly_agg_ind9 on monthly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, time_month);
drop index monthly_agg_ind10 on monthly_agg;
create index monthly_agg_ind10 on monthly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, time_month);
drop index monthly_agg_ind11 on monthly_agg;
create index monthly_agg_ind11 on monthly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, time_month);
drop index monthly_agg_ind12 on monthly_agg;
create index monthly_agg_ind12 on monthly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, time_month);
drop index monthly_agg_ind13 on monthly_agg;
create index monthly_agg_ind13 on monthly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, time_month);
drop index monthly_agg_ind14 on monthly_agg;
create index monthly_agg_ind14 on monthly_agg(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, time_month);
drop index monthly_agg_ind15 on monthly_agg;
create index monthly_agg_ind15 on monthly_agg(Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, Key15, time_month);
drop index monthly_agg_ind16 on monthly_agg;
#create index monthly_agg_ind16 on monthly_agg(TopId);
drop index monthly_agg_ind17 on monthly_agg;
#create index monthly_agg_ind17 on monthly_agg(counter);
drop index monthly_agg_ind18 on monthly_agg;
#create index monthly_agg_ind18 on monthly_agg(time_month);
drop index monthly_agg_ind19 on monthly_agg;
#create index monthly_agg_ind19 on monthly_agg(agg_type);
drop index monthly_agg_ind20 on monthly_agg;
#create index monthly_agg_ind20 on monthly_agg(countTopId);

