use test;

drop index meas_vals_ind1 on meas_vals;
create index meas_vals_ind1 on meas_vals(meas_time);
drop index meas_vals_ind2 on meas_vals;
create index meas_vals_ind2 on meas_vals(agg_hour);
drop index meas_vals_ind3 on meas_vals;
create index meas_vals_ind3 on meas_vals(agg_day);
drop index meas_vals_ind4 on meas_vals;
create index meas_vals_ind4 on meas_vals(agg_week);
drop index meas_vals_ind5 on meas_vals;
create index meas_vals_ind5 on meas_vals(agg_month);
drop index meas_vals_ind6 on meas_vals;
create index meas_vals_ind6 on meas_vals(topid, Key1, meas_time, val);
drop index meas_vals_ind7 on meas_vals;
create index meas_vals_ind7 on meas_vals(topid, Key1, Key2, meas_time, val);
drop index meas_vals_ind8 on meas_vals;
create index meas_vals_ind8 on meas_vals(topid, Key1, Key2, Key3, meas_time, val);
drop index meas_vals_ind9 on meas_vals;
create index meas_vals_ind9 on meas_vals(topid, Key1, Key2, Key3, Key4, meas_time, val);
drop index meas_vals_ind10 on meas_vals;
create index meas_vals_ind10 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, meas_time, val);
drop index meas_vals_ind11 on meas_vals;
create index meas_vals_ind11 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, meas_time, val);
drop index meas_vals_ind12 on meas_vals;
create index meas_vals_ind12 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, meas_time, val);
drop index meas_vals_ind13 on meas_vals;
create index meas_vals_ind13 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, meas_time, val);
drop index meas_vals_ind14 on meas_vals;
create index meas_vals_ind14 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, meas_time, val);
drop index meas_vals_ind15 on meas_vals;
create index meas_vals_ind15 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, meas_time, val);
drop index meas_vals_ind16 on meas_vals;
create index meas_vals_ind16 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, meas_time, val);
drop index meas_vals_ind17 on meas_vals;
create index meas_vals_ind17 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, meas_time, val);
drop index meas_vals_ind18 on meas_vals;
create index meas_vals_ind18 on meas_vals(topid, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, meas_time, val);
drop index meas_vals_ind19 on meas_vals;
create index meas_vals_ind19 on meas_vals(topid, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, meas_time, val);
drop index meas_vals_ind20 on meas_vals;
create index meas_vals_ind20 on meas_vals(topid, Key3, Key4, Key5, Key6, Key7, Key8, Key9, Key10, Key11, Key12, Key13, Key14, Key15, meas_time, val);
drop index meas_vals_ind21 on meas_vals;
#create index meas_vals_ind21 on meas_vals(TopId);
drop index meas_vals_ind22 on meas_vals;
#create index meas_vals_ind22 on meas_vals(counter);
drop index meas_vals_ind23 on meas_vals;
#create index meas_vals_ind23 on meas_vals(val);
